kind: Service
apiVersion: v1
metadata:
  name: demo-springboot
  namespace: bigops
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31001
  selector:
    app: demo-springboot
